services:
  test_wallet_db:
    image: postgres:14
    container_name: wallet_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d # Подключение скриптов для инициализации
    restart: unless-stopped


  wallet_fastapi:
    build: ./
    container_name: wallet
    depends_on:
      - test_wallet_db
#    command: bash -c 'while !</dev/tcp/test_wallet_db/5432; do sleep 1; done; alembic upgrade head  && uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    restart: always
    env_file:
      - .env
volumes:
  postgres_data: